spring:
  security:
    oauth2:
      client:
        registration:
          tid:
            client-id: ${TID_CLIENT_ID}
            client-secret: ${TID_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${TID_REDIRECT_URI}
            client-name: tid
            client-authentication-method: client_secret_post

        provider:
          tid:
            authorization-uri: ${}
            token-uri: ${}
            user-info-uri: ${}
            user-name-attribute: %{}
            jwk-set-uri: ${}
